spring:
  application:
    name: ddakdae
  config:
    import: classpath:application-secret-api.yml

  jpa:
    hibernate:
      ddl-auto: none  # 또는 validate, create, create-drop 중 하나
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  data:
    redis:
#        host: redis-master.redis.svc.cluster.local
      host: localhost
      port: 6379
